#!/bin/sh

set -e
set -x

yum config-manager --set-enabled PowerTools

yum update

yum install --assumeyes  \
	ca-certificates  \
	cryptsetup       \
	curl             \
	gcc              \
	git              \
	gpgme-devel      \
	iptables         \
	libseccomp-devel \
	libuuid-devel    \
	make             \
	openssl-devel    \
	pkgconfig        \
	squashfs-tools   \
	sudo

rm -rf /var/cache/yum

curl --location https://github.com/gotestyourself/gotestsum/releases/download/v0.3.5/gotestsum_0.3.5_linux_amd64.tar.gz |
	tar -xOzf - gotestsum > /usr/bin/gotestsum

chown root:root /usr/bin/gotestsum

chmod 0755 /usr/bin/gotestsum

echo 'ALL ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers
