#!/bin/sh

set -e
set -x

apt-get update

# These are required by tests:
#
# cryptsetup
# debootstrap
# e2fsprogs
# yum
# zypper
#
# zypper is not available on Ubuntu 18.04, but it is available in latter
# versions.

env DEBIAN_FRONTEND=noninteractive apt-get install -f -y --no-install-recommends \
	build-essential                                                          \
	ca-certificates                                                          \
	cryptsetup                                                               \
	curl                                                                     \
	debootstrap                                                              \
	e2fsprogs                                                                \
	git                                                                      \
	libgpgme11-dev                                                           \
	libseccomp-dev                                                           \
	libssl-dev                                                               \
	pkg-config                                                               \
	squashfs-tools                                                           \
	sudo                                                                     \
	tzdata                                                                   \
	uuid-dev                                                                 \
	yum

apt-get clean

rm -rf /var/lib/apt/lists/*

curl --location https://github.com/gotestyourself/gotestsum/releases/download/v0.3.5/gotestsum_0.3.5_linux_amd64.tar.gz |
	tar -xOzf - gotestsum > /usr/bin/gotestsum

chown root:root /usr/bin/gotestsum

chmod 0755 /usr/bin/gotestsum

echo 'ALL ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers

# There's code in singularity that assumes that if rpm is installed on
# the system it will behave like rpm on a rpm-based distribution. Debian
# and derivatives configure rpm in a way that makes sense in those
# systems, but it's not the same as in rpm-based distributions.
#
# The tests for the yum conveyor actually check that rpm behaves in that
# particular way, and FAIL otherwise.
#
# Work around this issue by adding macros to satisfy this assumption.
mkdir -p /etc/rpm
cat > /etc/rpm/macros <<EOT
%_var /var
%_dbpath %{_var}/lib/rpm
EOT
