name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    name: Build from Dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Check Dockerfile
      run: test -f Dockerfile
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sylabs/buildenv:$(date +%s)
